#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea add circle 12025 0 -102 3 witch_and_clay'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Jokes about libraries are long overdue. (ticking area added)'`echo -ne '\015'`
