#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea add circle -56 0 792 2 cows'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Secret Cow Level Unlocked (ticking area added)'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'tickingarea add circle -136 0 792 2 sheep'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say black sheep wall (ticking area added)'`echo -ne '\015'`
