#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea add -32 0 -32 15 0 15 wood_and_kelp'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Got wood? (ticking area added)'`echo -ne '\015'`
