#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea add 128 0 64 159 0 95 sim_tower'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Maxis SimTower remake incoming. (ticking area added)'`echo -ne '\015'`
