#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea add 1824 0 1712 1887 0 1807 ice_farm'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Ice to see you. (ticking area added)'`echo -ne '\015'`
