#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea remove witch_and_clay'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Sorry, that book is checked out. (ticking area removed)'`echo -ne '\015'`
