#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea remove sim_tower'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Yoot Saito logging out (ticking area removed)'`echo -ne '\015'`
