#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea remove wood_and_kelp'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say I have been bamboozled! (ticking area removed)'`echo -ne '\015'`
