#!/bin/bash
screen -S minecraft_server -X stuff 'tickingarea remove ice_farm'`echo -ne '\015'`
screen -S minecraft_server -X stuff 'say Talk about a cold shoulder. (ticking area removed)'`echo -ne '\015'`
